### ISSUE TITLE
玩家進入伺服器後區塊不加載

### ISSUE THREAD

**Issue by HaHaWTH** [Imanity-Software/raytrace-antixray-git#2]
### Stacktrace 堆疊追蹤

https://mclo.gs/IG63oZa

### Plugin list 插件列表

在僅帶有
RaytraceAntixray: 0.7.0-beta
FairyLib: v0.7.4b1-SNAPSHOT
ProtocolLib: 5.2.1-SNAPSHOT-689
這些插件的情況下可以複現

### RaytraceAntiXray 的版本

RaytraceAntixray: 0.7.0-beta
FairyLib: v0.7.4b1-SNAPSHOT

可能關聯的插件：
ProtocolLib: 5.2.1-SNAPSHOT-689

### Spigot 的版本和分支名稱

Paper 1.20.6 - mojmap

### Agreements 同意事項

- [X] 我目前運行的 RaytraceAntiXray 版本是目前的最新版.
- [X] 我有在這個 Issue Tracker 中搜尋過並沒有發現類似的問題回報.

**Comment by LeeGodSRC** [comment]
Should be fixed by latest version
