### ISSUE TITLE
Entity culling hides players with glowing

### ISSUE THREAD

**Issue by zylstra1313** [Imanity-Software/raytrace-antixray-git#4]
### Expected behavior

If a player has glowing they should not be hidden by entity culling.

### Observed/Actual behavior

Players with glowing are hidden by entity culling.

### Steps/models to reproduce

Give a player glowing and have them walk behind a wall.

### Plugin list

RtAntixray
fairy-lib

### RaytraceAntiXray version

0.10.2

### Spigot version & fork name

Paper 1.20.2

### Agreements

- [x] I am running the latest version of Raytrace AntiXray available.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by LeeGodSRC** [comment]
Will be added by `0.13.5beta`.
