### ISSUE TITLE
View Distance and Simulation Distance Mismatch Causes Display Issues

### ISSUE THREAD

**Issue by lulu2002** [Imanity-Software/raytrace-antixray-git#8]
### Expected behavior

When the `view distance` and `simulation distance` are set to different values, I expected the server to smoothly render items and blocks in-game without sudden appearance issues.

### Observed/Actual behavior

When the `view distance` is set to 8 and the `simulation distance` is set to 6, it causes items and blocks to suddenly appear. However, when both distances are set to 8, the issue resolves and everything works as expected.

### Steps/models to reproduce

1. Set `view distance` to 8 and `simulation distance` to 6 in the server configuration.  
2. Observe the sudden appearance of items and blocks.  
3. Set both `view distance` and `simulation distance` to 8.  
4. Notice that the issue is resolved.

### Plugin list

No Information.

### RaytraceAntiXray version

Waiting...

### Spigot version & fork name

Waiting...

### Agreements

- [X] I am running the latest version of Raytrace AntiXray available.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

https://github.com/user-attachments/assets/2b051da8-3499-4c56-b94b-b136c691ea63

**Comment by ghost** [comment]
Plugin list:
RaytraceAntiXray, Raytrace Entity Culling Addon, Raytrace Tile Culling Addon

RaytraceAntiXray version:
0.14.0beta

Spigot version & fork name:
Leaf
Link: https://github.com/Winds-Studio/Leaf

**Comment by LeeGodSRC** [comment]
Can you try `0.15.0beta`?

**Comment by lamlam098** [comment]
This bug is still not fixed in version 0.15.0beta . even when View distance = simulation distance

**Comment by LeeGodSRC** [comment]
This issue should be fixed by `0.15.2beta`
